#!/usr/bin/env bash

set -euo pipefail

set_pipeline() {
  fly -t scs set-pipeline -p service-instance-reaper -c pipeline.yml
}

main() {
  pushd "$(dirname "$0")/../ci" > /dev/null

  set_pipeline

  popd > /dev/null
}

main
